/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_proj2;

import java.time.LocalTime;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //LocalTime currentTime = new LocalTime();
        LocalTime currentTime = LocalTime.now(); // Use static method now() to get the current time
        System.out.println("The current local time is: " + currentTime);

    
        System.out.println("Hello World!");
    }
}
